INSERT INTO SURF_SPOT(SURF_SPOT_ID, IMG_PATH, NAME, NAME, ADDRESS, VIEW_COUNTS) VALUES (1,'썸네일주소1', '제주도1', '제주광역시어쩌고', 0);
INSERT INTO SURF_SPOT(SURF_SPOT_ID, IMG_PATH, NAME, NAME, ADDRESS, VIEW_COUNTS) VALUES (2,'썸네일주소2', '부산1', '부산광역시어쩌고', 0);
INSERT INTO SURF_SPOT(SURF_SPOT_ID, IMG_PATH, NAME, NAME, ADDRESS, VIEW_COUNTS) VALUES (3,'썸네일주소3', '대구1', '대구광역시어쩌고', 0);