INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(1,'양양군',90,136,'강원도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(2,'강릉군',95,129,'강원도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(3,'고성군',86,144,'강원도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(4,'태안시',46,109,'충청남도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(5,'포항시북구',102,96,'경상북도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(6,'서귀포시',51,32,'제주특별자치도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(7,'제주시',51,38,'제주특별자치도');
INSERT INTO region(REGION_ID,REGION_CHILD,NX,NY,REGION_PARENT) VALUES(8,'해운대구',61,126,'부산광역시');
